### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [nmHolman/prj-rev-bwfs-dasmoto#2]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/nmHolman/prj-rev-bwfs-dasmoto/blob/2e0bfda6b82917e6b3913542d505c160c4a3cfd6/dasmotoArts/index.html#L15

Note: there's usually processors that you can use to filter those out for you in production environments, but keep this in mind

**Comment by nmHolman** [comment]
Good to know. Thanks for the reference!
